// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTFQudDe_YdN7QQyUHfE1XsNn-WzW2U7w',
    appId: '1:920223920591:web:5223955fa6e7119b4222ba',
    messagingSenderId: '920223920591',
    projectId: 'usta-app-bc5cf',
    authDomain: 'usta-app-bc5cf.firebaseapp.com',
    storageBucket: 'usta-app-bc5cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoU5Nc0bPcl3bzizzhV3yDzO6r09xT81I',
    appId: '1:920223920591:android:7d209e57d9f5d7d94222ba',
    messagingSenderId: '920223920591',
    projectId: 'usta-app-bc5cf',
    storageBucket: 'usta-app-bc5cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjvWeXfwF6Pao7dBzMQ_htz5mNuwmpDj8',
    appId: '1:920223920591:ios:e1897930abe57cc84222ba',
    messagingSenderId: '920223920591',
    projectId: 'usta-app-bc5cf',
    storageBucket: 'usta-app-bc5cf.firebasestorage.app',
    iosBundleId: 'com.example.ustaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjvWeXfwF6Pao7dBzMQ_htz5mNuwmpDj8',
    appId: '1:920223920591:ios:e1897930abe57cc84222ba',
    messagingSenderId: '920223920591',
    projectId: 'usta-app-bc5cf',
    storageBucket: 'usta-app-bc5cf.firebasestorage.app',
    iosBundleId: 'com.example.ustaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTFQudDe_YdN7QQyUHfE1XsNn-WzW2U7w',
    appId: '1:920223920591:web:e47759d2da6ce02a4222ba',
    messagingSenderId: '920223920591',
    projectId: 'usta-app-bc5cf',
    authDomain: 'usta-app-bc5cf.firebaseapp.com',
    storageBucket: 'usta-app-bc5cf.firebasestorage.app',
  );
}
